sass:
  load_paths:
    - _sass
    - node_modules
exclude: 
  - node_modules
  - vendor
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Request-Method: "GET, POST, PATCH, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers: "Origin, Content-Type, X-Auth-Token, Authorization"
